export const types = {
    USER_LOGIN:'USER_LOGIN',
    UPDATE_USER_INFO : 'UPDATE_USER_INFO',
    UPDATE_EMAIL:'UPDATE_EMAIL',
    UPDATE_PHONE:'UPDATE_PHONE',
    UPDATE_NICKNAME:'UPDATE_NICKNAME',
    LOGOUT : 'LOGOUT',
    UPDATE_MY_LOCATION : 'UPDATE_MY_LOCATION',
    SELECT_MY_LOCATION : 'SELECT_MY_LOCATION',
    DELETE_MY_LOCATION : 'DELETE_MY_LOCATION',
    DELETE_ALL : 'DELETE_ALL',
    POST_PRODUCT : 'POST_PRODUCT',
}
